version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        # schema: public -- used to be in, now we remove it
        databases:
          default:
            connector: postgres
            host: ec2-54-246-84-100.eu-west-1.compute.amazonaws.com
            database: deg8heqk76viaa
            user: ciqfpqdhamulfv
            password: f25ee9b06098938d018d4cc87e96f5b3bdbb5633f8663d6990103b89300df675
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true